export { default as SButton, ButtonGroup as SButtonGroup } from './button'
export { default as SSpace } from './space'
export { default as SInput } from './input'
export { default as STrigger } from './trigger'
export { default as STree } from './tree'
export { default as SSwitch } from './switch'
